version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}
        NODE_ENV: ${NODE_ENV}
        JWT_SECRET: ${JWT_SECRET}
        ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC: ${ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
        APPLE_TEAM_ID: ${APPLE_TEAM_ID}
        APPLE_KEY_ID: ${APPLE_KEY_ID}
        APPLE_PRIVATE_KEY: ${APPLE_PRIVATE_KEY}
        FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
        FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
    env_file:
      - .env.dev

    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC: ${ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_PRIVATE_KEY: ${APPLE_PRIVATE_KEY}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: ${DATABASE_HOST}
      PMA_USER: ${DATABASE_USERNAME}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
